//Author: Mark Collier 
//Purpose: To post and get data from an external service API. 
public class Rest{ 
	public String url = 'https://th-apex-http-callout.herokuapp.com/animals'; 
	public Rest(String urlParameter){ 
		url = urlParameter; 
		main(); 
	} 
	//this method is part of the initialisation for this class and will be executed when the class is initialised. 
	public void main(){ 
		//tODO: Control and direct the operations that are required in order to meet the intended purpose as mentioned above 
	} 
}